title: Shuzhan Yang
description: Web & 3d Designer
site_title: 'Shuzhan Yang'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: yangshuzhan
blog_url: https://www.nagekar.com
email: 1534596814@qq.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/QQ截图20220704232207.png

# Google Analytics ID
google_analytics: 
